// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH9dHxFhhTVT_vU0leSZWZBtOytWj_MQw',
    appId: '1:49789057845:web:eb90dd06254ceda61aaa7c',
    messagingSenderId: '49789057845',
    projectId: 'database-app-orvix-ewf',
    authDomain: 'database-app-orvix-ewf.firebaseapp.com',
    storageBucket: 'database-app-orvix-ewf.firebasestorage.app',
    measurementId: 'G-8ST79KBD06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZdfSLO-cluPQbX-K8dmuH_bMWdQ22EOg',
    appId: '1:49789057845:android:5c0c4861fcef2e861aaa7c',
    messagingSenderId: '49789057845',
    projectId: 'database-app-orvix-ewf',
    storageBucket: 'database-app-orvix-ewf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuAzy9NU_NjeJDBnkFlctYwHOVXJMuYQA',
    appId: '1:49789057845:ios:ed8cf4f1590944951aaa7c',
    messagingSenderId: '49789057845',
    projectId: 'database-app-orvix-ewf',
    storageBucket: 'database-app-orvix-ewf.firebasestorage.app',
    iosBundleId: 'com.example.appPtEwf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuAzy9NU_NjeJDBnkFlctYwHOVXJMuYQA',
    appId: '1:49789057845:ios:ed8cf4f1590944951aaa7c',
    messagingSenderId: '49789057845',
    projectId: 'database-app-orvix-ewf',
    storageBucket: 'database-app-orvix-ewf.firebasestorage.app',
    iosBundleId: 'com.example.appPtEwf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH9dHxFhhTVT_vU0leSZWZBtOytWj_MQw',
    appId: '1:49789057845:web:266371262ce1c06f1aaa7c',
    messagingSenderId: '49789057845',
    projectId: 'database-app-orvix-ewf',
    authDomain: 'database-app-orvix-ewf.firebaseapp.com',
    storageBucket: 'database-app-orvix-ewf.firebasestorage.app',
    measurementId: 'G-7CFHEE7ZEJ',
  );
}
